DROP FUNCTION IF EXISTS ECElGamal_Agr;
CREATE AGGREGATE FUNCTION ECElGamal_Agr
RETURNS STRING
SONAME 'ECElgamalUDF.so';

DROP FUNCTION IF EXISTS Paillier_agr;
CREATE AGGREGATE FUNCTION Paillier_agr
RETURNS STRING
SONAME 'PaillierUDF.so';

DROP FUNCTION IF EXISTS mOPE_MIN;
CREATE AGGREGATE FUNCTION mOPE_MIN
RETURNS INTEGER
SONAME 'mOPE_AGR.so';

DROP FUNCTION IF EXISTS mOPE_MAX;
CREATE AGGREGATE FUNCTION mOPE_MAX
RETURNS INTEGER 
SONAME 'mOPE_AGR.so';

DROP FUNCTION IF EXISTS CRT_GAMAL_SUM;
CREATE AGGREGATE FUNCTION CRT_GAMAL_SUM
RETURNS STRING
SONAME 'CRT_GAMAL_AGR.so';

DROP FUNCTION IF EXISTS PRE_REL_SUM;
CREATE AGGREGATE FUNCTION PRE_REL_SUM
RETURNS STRING
SONAME 'PRE_RELIC_UDF.so';

DROP FUNCTION IF EXISTS PRE_REL_REENC;
CREATE FUNCTION PRE_REL_REENC
RETURNS STRING
SONAME 'PRE_RELIC_UDF.so';
