DROP FUNCTION IF EXISTS PRE_SUM;
CREATE AGGREGATE FUNCTION PRE_SUM
RETURNS STRING
SONAME 'PRE_UDF.so';

DROP FUNCTION IF EXISTS PRE_SUM_CACHED;
CREATE AGGREGATE FUNCTION PRE_SUM_CACHED
RETURNS STRING
SONAME 'PRE_UDF.so';

DROP FUNCTION IF EXISTS ECElGamal_Agr;
CREATE AGGREGATE FUNCTION ECElGamal_Agr
RETURNS STRING
SONAME 'ECElgamalUDF.so';

DROP FUNCTION IF EXISTS Paillier_agr;
CREATE AGGREGATE FUNCTION Paillier_agr
RETURNS STRING
SONAME 'PaillierUDF.so';

DROP FUNCTION IF EXISTS mOPE_MIN;
CREATE AGGREGATE FUNCTION mOPE_MIN
RETURNS INTEGER
SONAME 'mOPE_AGR.so';

DROP FUNCTION IF EXISTS mOPE_MAX;
CREATE AGGREGATE FUNCTION mOPE_MAX
RETURNS INTEGER 
SONAME 'mOPE_AGR.so';

DROP FUNCTION IF EXISTS CRT_GAMAL_SUM;
CREATE AGGREGATE FUNCTION CRT_GAMAL_SUM
RETURNS STRING
SONAME 'CRT_GAMAL_AGR.so';

DROP FUNCTION IF EXISTS CRT_GAMAL_SUM_160;
CREATE AGGREGATE FUNCTION CRT_GAMAL_SUM_160
RETURNS STRING
SONAME 'CRT_GAMAL_AGR_160.so';

DROP FUNCTION IF EXISTS CRT_GAMAL_SUM_224;
CREATE AGGREGATE FUNCTION CRT_GAMAL_SUM_224
RETURNS STRING
SONAME 'CRT_GAMAL_AGR_224.so';


DROP FUNCTION IF EXISTS PRE_SUM;
CREATE AGGREGATE FUNCTION PRE_SUM
RETURNS STRING
SONAME 'PRE_UDF.so';

